# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions

# timestamp function for backing up files
alias timestamp='date +%F-%H%M'

# shortcut the dirs stack management
alias pu='pushd'
alias po='popd'

# Some shortcuts for different directory listings
alias ls='ls -hF --color=tty'                 # classify files in colour
alias ll='ls -l'                              # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'                              #

# Ruby Bundler shortcuts
alias b="bundle"
alias bi="b install --path vendor"
alias bil="bi --local"
alias bu="b update"
alias be="b exec"
alias binit="bi && b package && echo 'vendor/ruby' >> .gitignore"

# shorthand rails project creation
function railsapp {
    template=$1
    appname=$2
    shift 2
    rails $appname -m http://github.com/dznz/rails-templates/raw/master/$template.rb $@
}
