# ~/.bash_profile: executed by bash for login shells.

# source the users bashrc if it exists
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export PATH

export EDITOR=/usr/bin/vim
